### ISSUE TITLE
Clashes with vim-javascript

### ISSUE THREAD

**Issue by jwoudenberg** [bigfish/vim-js-context-coloring#16]
Thanks for writing this, I find it incredibly useful. I have it disabled by default and use the toggle to use it as a code analyzing tool.

One problem though, I'm also using [vim-javascript](https://github.com/pangloss/vim-javascript) which has nicer (I think) syntax highlighting. The problem is that this plugin seems to have vim default to its default syntax highlighting for javascript, even when the plugin is disabled in the vimrc and a new instance of vim is launched. Can this be helped?

**Comment by jwoudenberg** [comment]
Thanks for your response, sorry for my own late response. I did some additional tests and found out what's happening: whether I see vim's default js syntax highlighter or vim-javascript's, depends on the order in which I load the vim-javascript and the vim-js-context-coloring plugins.

I'm running vim version 7.4.580. I use [vim-plugg](https://github.com/junegunn/vim-plug) as a plugin manager, but before I have had the same issue using pathogen. I'm running the latest version of all my plugins, freshly pulled from git.

Running just vim-javascript and vim-js-context-coloring, when I load vim-javascript first, it's syntax highlighter is ignored and vim's default highlighter is used when toggling back and forth (regardless of whether I set `g:js_context_colors_enabled=0` or not). When I load vim-js-context-coloring first though, vim-javascript's highlighter is used.

So, changing the order fixes the issue for me.

**Comment by bigfish** [comment]
Well, I'm glad you found a workaround, finally! I still can't see the issue. When disabling itself, my plugin executes these commands, which you can also execute manually.

let g:js_context_colors_enabled = 0
syntax enable

When the global flag is disabled, my plugin will not do anything in its syntax file, so when 'syntax enable' re-initializes the syntax, it should find vim-javascript 's syntax. Unless vim-javascript is not being added to the runtimepath. When you execute 

:echo &runtimepath

Does vim-javascript's directory show up?

**Comment by bigfish** [comment]
I think a closely related -- if not causative --  issue is that when the plugin is disabled, it was calling 'syntax enable' which resets all syntax highlighting for all buffers. It then looks for the first syntax/javascript.vim in 'runtimepath' to execute. Depending on the order of vim-javascript in your runtimepath, vs default $VIMRUNTIME, it may have reset to default vim js syntax. 

So I've just committed a change to not call 'syntax enable' when disabling, but just clear the current buffers syntax and then reload syntax/javascript.vim syntax. Which syntax is loaded will depend on the runtimepath order, but at least it will only affect the current buffer! 

I think I'll close this issue then, since I believe it is fixed, but if users still encounter it, they will hopefully find this thread and use the workaround you found.

**Comment by jwoudenberg** [comment]
Hi @bigfish. Sorry for the late response, I was on a holiday. Thanks for figuring it out :+1: .
